name: Resorce Group will be create.

on:
  push:
    branches:
    - main
    - feature/*
    
  workflow_dispatch:


env:
  workdir: environment/dev

  
jobs:
 terraform-init-plan:
    name: Terraform init validate plan
    #runs-on: [ self-hosted, Windows, X64, ghatest, manish ]
    runs-on: self-hosted
    steps:
      
      - name: clone repo.
        uses: actions/checkout@v5
        
      - name: AZ Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: ${{ env.workdir }}
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: ${{ env.workdir }}


    

